config/routes.rb
Chatroom::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admins, :controllers => {:sessions => "admins/sessions"}#, :path_names => { :sign_in => 'login'}

  devise_for :users#, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  match ':controller(/:action(/:id))'

  root :to => "users#index"
end

app/views/layouts/_admin_navi.html.erb
<div class="top">
  <h1>
    <a href="/admin"><img src="/admin/images/logo.jpg" alt="SchoolCity管理画面" /></a>
    <%if current_admin.class.to_s != "Admin" && Info.check_backstage(current_admin)%>
        <span style="color:#ff0000; font-size: 12px; margin-left: 30px; font-weight: normal;">管理者向けのお知らせがあります。<a href="/admin/info/list">こちら</a>からご確認ください。</span>
    <%end%>
  </h1>
  <div class="topInfo">
    <b><%= current_admin.email %></b>
    <span class="links"><a href=''>プロフィール編集</a></span>
    <span class="links"><a href="/admin/admins/change_password">パスワードの変更</a></span>
    <span class="links"><a href="/admin/admins/logout">ログアウト</a></span> </div>
</div>
<div class="mainNav">
  <ul class="manager clearfix">
    <li class="nav_admin"><a href="/admins/index">企业管理</a></li>
    <li class="nav_user"><a href="/admin/user/list">用户管理</a></li>
    <li class="nav_task"><a href="/admin/task/index">任务管理</a></li>
    <li class="nav_file"><a href="/admin/file/index">文件管理</a></li>
    <li class="nav_message"><a href="/admin/message/index">消息管理</a></li>
    <li class="nav_logout"><a href="/admin/admin/logout">退出</a></li>
  </ul>
</div>
<div class="subnav">
  <div id="show_user" class="items" style="display:none;">
    <ul class="manager clearfix">
      <li><a id="nav_user_list" href="/admin/user/list">用户一览</a></li>
          <li><a id="user_new" href="/admin/user/sign_request">新建用户</a></li>
          <li><a id="file_upload" href="/admin/user/user_import_csv">批量新建用户（CSV）</a></li>
          <li><a id="group_list" href="/admin/user/group_list">群组一览</a></li>
          <li><a id="group_new" href="/admin/user/group_new">新建群组</a></li>
    </ul>
  </div>
  <div id="show_company" class="items" style="display:none;">
    <ul class="manager clearfix">
      <li><a id="nav_company_list" href="/admins/index">企业管理者一览</a></li>
      <li><a id="company_new" href="/admins/new">新建企业管理者</a></li>
    </ul>
  </div>
  <div id="show_task" class="items" style="display:none;">
    <ul class="manager clearfix">
      <li><a id="nav_task_list" href="/admin/task/index">任务一览</a></li>
    </ul>
  </div>
  <div id="show_file" class="items" style="display:none;">
    <ul class="manager clearfix">
      <li><a id="image_list" href="/admin/file/index">头像一览</a></li>
      <li><a id="file_list" href="/admin/file/document_list">文件一览</a></li>
    </ul>
  </div>
  <div id="show_message" class="items" style="display:none;">
    <ul class="manager clearfix">
      <li><a id="nav_message_list" href="/admin/message/index">消息一览</a></li>
    </ul>
  </div>
</div>
<script type="text/javascript">
    var patrn = /\/admin\/([^\/]+)\/.+/;
    str = patrn.exec(window.location.pathname) ;
    if(str){
        switch(str[1]){
            case 'admin':
                $(".nav_admin a")[0].className = "on";
                break
            case 'user':
                $(".nav_user a")[0].className = "on";
                break
            case 'task':
                $(".nav_task a")[0].className = "on";
                break
            case 'files':
                $(".nav_files a")[0].className = "on";
                break
            case 'message':
                $(".nav_message a")[0].className = "on";
                break
            case 'admin':
                $(".nav_admins a")[0].className = "on";
                break

        }
    };
</script>

app/views/layouts/_global_header.html.erb
<div id="_inner" role="banner" class="inner">
  <h1 id="_logo" style="">
    <img class="nosvgLogo_ChatRoom" src="/user/images/img_logo_ChatRoom.png" alt="ChatRoom" height="26" width="152">
  </h1>
  <div id="_headerSearch" class="headerSearch">
    <div class="search">
      <span class="icoFontSearch icSearch"></span>
      <span class="_cwSBCancel icoFontCancel icSearchCancel icoSizeLarge" style="display:none"></span>
      <input id="_search" class="_searchBox inputLong _cwSB searchBox" type="text" name="search" placeholder="搜索在线聊天用户名和留言信息" role="search">
    </div>
  </div>

  <div class="myStatus">
    <ul id="_adminNavi" role="navigation" class="adminNavi" style="">
      <li id="_openTaskWindow" role="button" aria-label="文件管理" class="linkstatus">
        <span class="ico35AdminTask"></span>
        <span id="_myAllTaskNum" class="numAdminCount" style="display: none;"></span>
      </li>
      <li id="_openFileWindow" role="button" aria-label="任务管理" class="linkstatus">
        <span class="ico35AdminFile"></span>
        <span id="_myFileNotice" class="numAdminCount" style="font-weight: bold; font-size: 13px; display: none;">&nbsp;!&nbsp;</span>
      </li>
      <li id="_openContactWindow" role="button" aria-label="联系人管理" class="_adminContact linkstatus">
        <span class="ico35AdminContact"></span>
        <span id="_myAllContactNum" class="numAdminCount" style="display: none;"></span>
      </li>
    </ul>
    <div id="_openInfomation" role="button" class="helpMenu">
      <span class="ico27Menu"></span>
    </div>
    <div id="_myStatusButton" class="cwTextUnselectable myStatusButton">
      <div id="_myStatusIcon" class="myStatusIcon">
        <% if current_user.photo_path.present? %>
            <%= image_tag(user.photo_path) %>
        <% else %>
            <img class=" avatarMedium _avatar _avatarAid548300" data-aid="548300" src="/user/images/117951.rsz.jpg">
        <% end %>
      </div>
      <p id="_myStatusName" class="myStatusName" style="">
        <span  class="_nameAid630659"><%= current_user.name %></span>
        <span class="openAction icoFontTriangleDown"></span>
      </p>
    </div>
  </div>

  <ul id="_myStatusBox" role="menu" class="myStatusMenu cwTextUnselectable">
    <li id="_myProfile" role="menuitem"><a>设置个人资料</a></li>
    <li id="_setting" role="menuitem"><a>个人设定</a></li>
    <li id="_openAdminMenu" role="menuitem"><a id="_openServiceAdmin">管理设定</a></li>
    <li id="_userAdminMenu" role="menuitem" style="display:none"><a href="https://www.ChatRoom.com/service/packages/ChatRoom/user_list.php" target="_blank">用户管理</a></li>
    <li id="_changeuiToOldMenu" role="menuitem"><a>返回旧版本</a></li>
    <li><a href="https://www.ChatRoom.com/?act=logout" role="menuitem">退出</a></li>
  </ul>
</div>

<div id="_informationBox" class="helpMenuBox" style="width: 350px;display: none;">
  <div id="_notificationArea" class="notificationArea" style="display: none">
    <div class="notificationInner">
      <p class="notificationTitle"><span class="icoFontInfo marginRight"></span>通知</p>
      <div id="_notificationContents" class="notificationContentsArea">
        <ul id="_notificationItemList"></ul>
      </div>
    </div>
  </div>
  <ul>
    <li><a id="_userGuideLink">Tips</a></li>
    <li><a href="http://help-en.ChatRoom.com/" target="_blank">帮助</a></li>
    <li><a href="https://www.ecstudio.jp/ssl/ChatRoom/support.html" target="_blank">客户咨询</a></li>
  </ul>
  <div class="feedbackArea">
    <p>客户意见及要求</p>
    <small>*请注意，您不会因为留意见而受到回信)</small>
    <textarea id="_feedbackMessage"></textarea>
    <div class="feedbackBtnArea">
      <div id="_submitFeedBackBtn" class="button btnPrimary">发送</div>
    </div>
  </div>
  <div class="helpMenuFooter clearfix">
    <small>© 2013 <a href="http://www.ChatRoom.com/about-us.html" target="_blank">ChatRoom</a></small>
    <ul class="socialArea">
      <li class="linkStatus"><a href="https://facebook.com/ChatRoom" target="_blank" class="_showDescription" aria-label="Facebook" data-delay="0"><span class="ico27FacebookWh"></span></a></li>
      <li class="linkStatus"><a href="https://twitter.com/ChatRoom_en" target="_blank" class="_showDescription" aria-label="Twitter" data-delay="0"><span class="ico27TwitterWh"></span></a></li>
      <li class="linkStatus"><a href="https://plus.google.com/101041432132486071752/" target="_blank" class="_showDescription" aria-label="Google+" data-delay="0"><span class="ico27GoogleWh"></span></a></li>
      <li class="linkStatus"><a href="http://blog-en.ChatRoom.com/" target="_blank" class="_showDescription" aria-label="Blog" data-delay="0"><span class="ico27BlogWh"></span></a></li>
    </ul>
  </div>
</div>

<div id="_searchResult" class="searchResultArea " style="display: none; left: 260px;">
  <ul id="_searchResultChatList" role="list" class="searchResultList searchResultChatList"></ul>
  <div id="_messageSearch" class="searchResultFooter selected">
    <span id="_messageSearchIcon" class="icoFontSearch " style="display: none"></span>
    <span id="_messageSearchHint" class="keywordSearchArea"></span>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% for name in [:info, :warning, :error, :notice] %>
	<% if flash[name] %>
    <div id='message' class="mt10">
        <div class='flash_notice'>
            <p>
                <%= flash[name] %>
            </p>
            <% flash[name] = nil %>
        </div>
    </div>
	<% end %>
<% end %>

app/views/layouts/_msg.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "ChatRoom", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= stylesheet_link_tag "admin/layout" %>
    <%= stylesheet_link_tag "admin/calendar" %>
    <%= stylesheet_link_tag "admin/shadowbox" %>
    <%= stylesheet_link_tag "admin/green" %>
    <%= stylesheet_link_tag "admin/pink" %>
    <%= stylesheet_link_tag "admin/blue" %>
    <%= stylesheet_link_tag "jquery-ui-timepicker" %>
    <%#= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'jquery-ui-1.10.3.custom.min' %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'admin/application' %>
    <%#= javascript_include_tag 'admin/calendar_date_select/calendar_date_select' %>
    <%#= javascript_include_tag 'admin/calendar_date_select/format_my_type' %>
    <%#3= javascript_include_tag 'admin/calendar_date_select/locale/jp' %>
    <%#= javascript_include_tag 'admin/ajaxzip2/ajaxzip2/ajaxzip2' %>
    <%#= stylesheet_link_tag "admin/calendar" %>
    <%= javascript_include_tag 'admin/common' %>
    <%= javascript_include_tag 'jQuery-Timepicker-Addon-master/jquery-ui-timepicker-addon.js' %>
    <!--script type="text/javascript">
        var CKEDITOR_BASEPATH = '/ckeditor/';
    </script-->
    <%#= javascript_include_tag 'ckeditor/ckeditor' %>
    <script type="text/javascript">
        //解决ie 中， image label无效的问题
        if(navigator.userAgent.indexOf("MSIE")>0) {
            document.observe('click', function(e) {
                if(e.findElement('img')){
                    var that = $(e.target);
                    var par = that.up(0);
                    //判断一定是label包裹的img标签被点击
                    if(par.nodeName == 'LABEL'){
                        var input_tag = $(that).previous(0);
                        var check_attr = input_tag.getAttribute("checked");
                        if(check_attr){
                            $(input_tag).removeAttr("checked");
                        }else{
                            $(input_tag).attr("checked", "checked");
                        }
                    }
                }
            });
        }
        function change_tr(val){
            if(val ==1)
            {
                $("#school").attr('style', '');
                $("social2").attr('style', 'display:none');
                $("social3").attr('style', 'display:none');
            }
            else{
                $("school").attr('style', 'display:none');
                $("social2").attr('style', '');
                $("social3").attr('style', '');
            }

        }
        // preload
        //add by zyc 20110707
        function preload(page_name){
            var img01 = new Image();
            var img02 = new Image();
            var img03 = new Image();
            var img04 = new Image();
            var img05 = new Image();
            var img06 = new Image();
            var img07 = new Image();
            var img08 = new Image();
            var img09 = new Image();
            var img10 = new Image();
            var img11 = new Image();
            var img12 = new Image();
            img01.src = "/admin/images/common/nav_course_on.jpg";
            img02.src = "/admin/images/common/nav_mater_on.jpg";
            img03.src = "/admin/images/common/nav_test_on.jpg";
            img04.src = "/admin/images/common/nav_live_on.jpg";
            img05.src = "/admin/images/common/nav_lib_on.jpg";
            img06.src = "/admin/images/common/nav_home_on.jpg";
            img07.src = "/admin/images/common/nav_stud_on.jpg";
            img08.src = "/admin/images/common/nav_order_on.jpg";
            img09.src = "/admin/images/common/nav_app_on.jpg";
            img10.src = "/admin/images/common/nav_master_on.jpg";
            img11.src = "/admin/images/common/nav_mess_on.jpg";
            img12.src = "/admin/images/common/nav_freepage_on.jpg";
        }
    </script>
  </head>
  <body onload="if (document.images)preload();">
    <div id="wrap">
      <div id="head"><%= render :partial => "/layouts/admin_navi" %></div>
	  <div id="content">
        <%= render :partial=> "/layouts/messages"%>
        <%= yield %>
      </div>
      <div id="footer">
        Copyright (C) 2013 With us Corporation. All rights reserved.
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatroom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
</div>
<div>
<%= yield %>
</div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>システムログイン</title>
  <%= stylesheet_link_tag "admin/layout" %>
  <%= stylesheet_link_tag "admin/login" %>
  <%= javascript_include_tag :defaults %>
</head>

<body class="login">
<div id="wrap">
  <div id="content">
    <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
    <% end %>
    <div class="loginBox">
      <%= yield %>
    </div>
  </div>
  <script  language="javascript" type="text/javascript">
      if($F('login')==''){
          $('login').focus();}
      else{ $('password').focus();}
      //if( window.location.protocol=="https:")
      //{
      //  $('ssl').replace('');
      // }
  </script>
  <div id="footer">
    Copyright (C) 2011 With us Corporation. All rights reserved.
  </div>
</div>
</body>
</html>

app/views/layouts/shadow.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><%#= page_title %></title>
    <%= stylesheet_link_tag "admin/layout" %>
    <%= stylesheet_link_tag "admin/sbox" %>
    <%= stylesheet_link_tag "admin/common" %>
    <%#= stylesheet_link_tag "user/chatwork_new.less" %>
    <%= stylesheet_link_tag "user/style2" %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'user/side_content' %>
  </head>

  <body>
    <div id="swrap">
      <div id="_contactWindow" class="contactWindow _cwFWInner floatWindowInner" style="left: 539px; right: 539px;" role="dialog" aria-label="コンタクト管理">
        <h1 class="contentHl floatContentH1"><span class="autotrim">コンタクト管理</span></h1>

        <div class="windowButton linkIconStatus">
          <span class="_cwFWButton icoFontCancel icoSizeLarge" data-cwui-fw-idx="-1" onclick="javascript:top.Shadowbox.close();"></span>
          <span class="icoTextHide" >閉じる</span>
        </div>
        <%= yield %>
      </div>
      <!--div class="btn_close">
        <a href="#" onclick="javascript:top.Shadowbox.close();">
          <img src="/admin/images/common/btn_close.gif" alt="閉じる" />
        </a>
      </div-->
    </div>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta charset="UTF-8">
  <meta name="application-name" content="ChatRoom">
  <meta name="application-url" content="#">
  <title id="title">ChatRoom</title>
  <%= stylesheet_link_tag "user/style2" %>
  <%= javascript_include_tag :defaults %>
  <!--shadowbox link -->
  <%= stylesheet_link_tag "admin/shadowbox" %>
  <%= javascript_include_tag 'admin/common' %>
  <%= javascript_include_tag 'admin/shadowbox/shadowbox' %>

  <%= javascript_include_tag 'user/side_content' %>
  <%= javascript_include_tag 'user/main_content' %>

  <!--calendar-->
  <%#= calendar_date_select_includes "default", :locale => 'ja'  %>
  <!--calendar end-->
  <script>
      // 下記2行を追加
      //jQuery.noConflict();
      //var j$ = jQuery;
  </script>
  <script type="text/javascript">
      Shadowbox.init({
          skipSetup: true,
          players: ["iframe"],
          modal:  true
      });
  </script>
</head>

<body class="zh-cn" style=""  >
<div id="_wrapper" class="wrapper" style="visibility: visible;">
  <div id="_globalHeader" class="globalHeader">
    <%= render :partial => "/layouts/global_header" %>
  </div>
  <%= yield %>
</div>

<script type="text/javascript">
    //自适应页面大小
    function setSideContent(){
        //网页可见区域高
        size=document.documentElement.clientHeight
        //设置style中height的值 ;
        document.getElementById("_wrapper").style.height=size+"px";
        document.getElementById("_sideContent").style.height=size-41+"px";
        if(document.getElementById("_overflow") != null){
            document.getElementById("_overflow").style.height=size-141+"px";
        }
        if(document.getElementById("_mainContent") != null){
        document.getElementById("_mainContent").style.height=size-41+"px";
        }
        if(document.getElementById("_subContent") != null){
        document.getElementById("_subContent").style.height=size-83+"px";
        }
        if(document.getElementById("_subContentArea") != null){
        document.getElementById("_subContentArea").style.height=size-83+"px";
        }
        if(document.getElementById("_roomListArea") != null){
        document.getElementById("_roomListArea").style.height=size-121+"px";
        }
        if(document.getElementById("_timeLine") != null){
            document.getElementById("_timeLine").style.height=size-220+"px";
        }
        if(document.getElementById("_emoticonList") != null){
            document.getElementById("_emoticonList").style.top=size-370+"px";
        }
    }
    setSideContent();
    window.onresize=setSideContent;


</script>
</body>
</html>